BankModel.Web/Controllers/SystemAdminController.cs
using BankModel.Web.ViewModels;
using BankModel.Models;
using BankModel.Web.Interfaces;
using BankModel.Web.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;

namespace BankModel.Web.Controllers
{
    [Authorize(Policy = "Administrator")]
    [Authorize(Policy = "HeadOffice")]
    public class SystemAdminController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ISystemAdminService _systemAdminService;
        private readonly IConfiguration _config;
        private readonly IValidationDictionary _validationDictionary;
        private readonly ISetupService _setupService;

        [TempData]
        public string StatusMessage { get; set; }
        public bool Result { get; set; }

        public SystemAdminController(
            UserManager<ApplicationUser> userManager, 
            SignInManager<ApplicationUser> signInManager, 
            IConfiguration config, 
            RoleManager<IdentityRole> roleManager,
            ISystemAdminService systemAdminService,
            ISetupService setupService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _config = config;
            _roleManager = roleManager;
            _setupService = setupService;
        }

        public SystemAdminController()
        {
            _systemAdminService = new SystemAdminService(new ModelStateWrapper(this.ModelState));
        }

        #region
        public JsonResult GetBranchStaff(string branch)
        {
            return Json(_systemAdminService.GetBranchStaff(branch));
        }

        [HttpGet]
        [Authorize(Policy = "SystemUsers")]
        public async Task<IActionResult> SystemUsers()
        {
            var user = await _userManager.GetUserAsync(User);
            if(user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            ViewData["Branches"] = new SelectList(_setupService.GetBranchNames(user.UserName));
            ViewData["Roles"] = new SelectList(_roleManager.Roles);
            var branchStaff = await _systemAdminService.GetBranchStaff(string.Empty);
            ViewData["Staff"] = new SelectList(branchStaff);

            var model = new SystemUsersViewModel{ StatusMessage = StatusMessage};
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SystemUsers(SystemUsersViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            var user = await _userManager.GetUserAsync(User);
            var branchStaff = await _systemAdminService.GetBranchStaff(string.Empty);

            if (!ModelState.IsValid)
            {
                ViewData["Branches"] = new SelectList(_setupService.GetBranchNames(user.UserName));
                ViewData["Roles"] = new SelectList(_roleManager.Roles);
                ViewData["Staff"] = new SelectList(branchStaff);
                return View(model);
            }

            model.ActionBy = user.UserName;
            Result = await _systemAdminService.CreateSystemUserAsync(model);

            if (Result == true)
            {
                StatusMessage = _config.GetSection("Messages")["Success"];
                return RedirectToAction(nameof(SystemUsers));
            }

            model = new SystemUsersViewModel { StatusMessage = "Error: Unable to create user account" };
            ViewData["Branches"] = new SelectList(_setupService.GetBranchNames(user.UserName));
            ViewData["Roles"] = new SelectList(_roleManager.Roles);
            ViewData["Staff"] = new SelectList(branchStaff);
            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = "SystemUsers")]
        public IActionResult SystemUsersListing()
        {
            return View(_systemAdminService.GetSystemUsers());
        }

        public async Task<IActionResult> SystemUserDetails(string user)
        {
            var userDetails = await _systemAdminService.GetUserDetails(user);
            return View(userDetails);
        }

        [HttpGet]
        [Authorize(Policy = "SystemUsers")]
        public async Task<IActionResult> UpdateSystemUser(string id)
        {
            var user = await _userManager.GetUserAsync(User);
            ViewData["Branches"] = new SelectList(_setupService.GetBranchNames(user.UserName));
            ViewData["Roles"] = new SelectList(_roleManager.Roles);
            var branchStaff = await _systemAdminService.GetBranchStaff(string.Empty);
            ViewData["Staff"] = new SelectList(branchStaff);
            var model = _systemAdminService.GetSystemUserWithDetails(id);
            return View(nameof(SystemUsers), model);
        }

        [HttpPost]
        [Authorize(Policy = "SystemUsers")]
        public async Task<IActionResult> UpdateSystemUser(SystemUsersViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);
            var branchStaff = await _systemAdminService.GetBranchStaff(string.Empty);

            if (!ModelState.IsValid)
            {
                ViewData["Branches"] = new SelectList(_setupService.GetBranchNames(user.UserName));
                ViewData["Roles"] = new SelectList(_roleManager.Roles);
                ViewData["Staff"] = new SelectList(branchStaff);
                return View(model);
            }

            model.ActionBy = user.UserName;
            Result = await _systemAdminService.UpdateSystemUserAsync(model);

            if (Result == true)
            {
                StatusMessage = _config.GetSection("Messages")["Success"];
                return RedirectToAction(nameof(SystemUsersListing));
            }

            model = new SystemUsersViewModel { StatusMessage = "Error: Unable to update user account" };
            ViewData["Branches"] = new SelectList(_setupService.GetBranchNames(user.UserName));
            ViewData["Roles"] = new SelectList(_roleManager.Roles);
            ViewData["Staff"] = new SelectList(branchStaff);

            return View(model);
        }


        [HttpGet]
        [Authorize(Policy = "SystemUsers")]
        public async Task<IActionResult> DropSystemUser(string ID)
        {
            Result = await _systemAdminService.DropSystemUserAsync(ID);
            if (Result)
            {
                StatusMessage = _config.GetSection("Messages")["Success"];
                return RedirectToAction(nameof(SystemUsersListing));
            }

            StatusMessage = "Error: Unable to delete system user";
            return RedirectToAction(nameof(SystemUsersListing));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SystemUserMaintenance(SystemUsersViewModel model, string returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            var user = await _userManager.GetUserAsync(User);
            var branchStaff = await _systemAdminService.GetBranchStaff(string.Empty);

            if (!ModelState.IsValid)
            {
                ViewData["Branches"] = new SelectList(_setupService.GetBranchNames(user.UserName));
                ViewData["Roles"] = new SelectList(_roleManager.Roles);
                ViewData["Staff"] = new SelectList(branchStaff);
                return View(nameof(SystemUsers), model);
            }

            //Maintain the system user
            model.ActionBy = user.UserName;
            Result = _systemAdminService.MaintainSystemUser(model);

            if (Result == true)
            {
                StatusMessage = _config.GetSection("Messages")["Success"];
                return RedirectToAction(nameof(SystemUsers));
            }

            model = new SystemUsersViewModel { StatusMessage = "Error: Unable to maintain user account" };
            ViewData["Branches"] = new SelectList(_setupService.GetBranchNames(user.UserName));
            ViewData["Roles"] = new SelectList(_roleManager.Roles);
            ViewData["Staff"] = new SelectList(branchStaff);
            return View(nameof(SystemUsers), model);
        }

        #endregion

        [HttpGet]
        [Authorize(Policy = "Parameter")]
        public async Task<IActionResult> SystemParameters()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }
            return View(_systemAdminService.GetApplicationParameters());
        }


        #region
        public async Task<JsonResult> GetRolePermissions(string role)
        {
            //Get the identity role 
            var requestedRole = await _roleManager.FindByNameAsync(role);
            var rolePermissions = await _roleManager.GetClaimsAsync(requestedRole);
            return Json(rolePermissions.Select(c => c.Type));
        }

        [HttpGet]
        [Authorize(Policy = "UserRole")]
        public async Task<IActionResult> UserRoles()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            ViewData["Users"] = new SelectList(_userManager.Users.Select(u => u.NormalizedUserName));

BankModel.Web/Views/SystemAdmin/SystemParameters.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration config
@{
    ViewData["Title"] = config.GetSection("AppInfo")["Title"];
}

<div class="container-fluid top-panel">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <h5>Application Parameters</h5>
                    </div>
                </div>
                <div class="panel-body">
                    <table data-toggle="table" data-class="table table-condensed"
                           data-striped="true" data-pagination="true" data-search="true" data-show-header="true"
                           data-show-column="true" data-show-refresh="true" data-show-toggle="true"
                           data-show-pagination-switch="true" data-id-field="Id">
                        <thead>
                            <tr>
                                <th data-id-field="ID">Parameter ID</th>
                                <th data-field="ParamName">Parameter Name</th>
                                <th data-field="ParamValue">Parameter Value</th>
                                <th data-field="ParamDesc">Remark</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var param in Model)
                            {
                                <tr id="@param.ID">
                                    <td>@param.ID</td>
                                    <td>@param.Name</td>
                                    <td>@param.Value</td>
                                    <td>@param.Description</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

BankModel.Web/Views/SystemAdmin/SystemUserDetails.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration config
@{
    ViewData["Title"] = config.GetSection("AppInfo")["Title"];
}

<div class="container-fluid top-panel">
    <div class="row">
        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title"><h5>User Details</h5></div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right text-right">ID</div>
                        <div class="col-sm-7 enquiry-value">@Model.ID</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right">Branch</div>
                        <div class="col-sm-7 enquiry-value">
                            Model.Branch
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right">Username</div>
                        <div class="col-sm-7 enquiry-value">@Model.Username</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right">Email</div>
                        <div class="col-sm-7 enquiry-value">@Model.Email</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right">Phone Number</div>
                        <div class="col-sm-7 enquiry-value">@Model.PhoneNumber</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right">Lockout Enabled</div>
                        <div class="col-sm-7 enquiry-value">@Model.LockoutEnabled</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right">Password Expiry</div>
                        <div class="col-sm-7 enquiry-value">@Model.PasswordExpiryDate.ToString("yyyy-MM-dd")</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right">Profile Image</div>
                        <div class="col-sm-7 enquiry-value">@Model.ProfileImage</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right">Transaction Limit</div>
                        <div class="col-sm-7 enquiry-value">@Model.TransactionLimit</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right">Approval Limit</div>
                        <div class="col-sm-7 enquiry-value">@Model.ApprovalLimit</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right">Date Created</div>
                        <div class="col-sm-7 enquiry-value">@Model.TransDate.ToString("yyyy-MM-dd")</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right">Approved By</div>
                        <div class="col-sm-7 enquiry-value">@Model.ApprovedBy</div>
                    </div>
                    <div class="row">
                        <div class="col-sm-offset-2 col-sm-3 enquiry-text text-right">Status</div>
                        <div class="col-sm-7 enquiry-value">@Model.Status</div>
                    </div>
                    <div class="panel-footer">
                        <a asp-action="UserRoles" asp-controller="SystemAdmin" class="btn btn-primary btn-sm pull-right">Back</a>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <h5>Roles and Permission</h5>
                    </div>
                </div>
                <div class="panel-body">
                    <label>Roles:</label>
                    @foreach (var role in Model.Roles)
                        {
                        <p>@role</p>

                        }
                    <hr />
                    <label>Permissions:</label>
                    @foreach (var permission in Model.Permissions)
                        {
                        <p>@permission</p>

                        }
                </div>
            </div>

        </div>

    </div>
</div>

BankModel.Web/Views/SystemAdmin/SystemUsers.cshtml
@model SystemUsersViewModel
@using Microsoft.Extensions.Configuration
@inject IConfiguration config
@{
    ViewData["Title"] = config.GetSection("AppInfo")["Title"];
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#Branch").change(function () {
            var selectedState = ("#Branch").valueOf();
            if ($("Branch").val() != "") {
                $.ajax
                    ({
                        url: "/SystemAdmin/GetBranchStaff",
                        type: "POST",
                        cache: false,
                        dataType: "JSON",
                        data: { branch: $("#Branch").val() },
                        success: function (Staff) {
                            $("#Staff").html("");
                            for (var i = 0; i < Staff.length; i++) {
                                $("#Staff").append("<option>" + Staff[i] + "</option>");
                            }
                        },
                        error: function (xhr, status) { alert(status); }
                    });
            };
        });

        $("#MaintenanceType").change(function () {
            if ($(this).val() == "UPDATE TRANSACTION LIMIT") {
                $("#LimitsModal").modal('show');
            }

            if ($(this).val() == "UPDATE APPROVAL LIMIT") {
                $("#LimitsModal").modal('show');
            }

            if ($(this).val() == "EXTEND PASSWORD EXPIRY") {
                $("#PasswordDaysModal").modal('show');
            }

            if ($(this).val() == "CHANGE BRANCH") {
                $("#BranchModal").modal('show');
            }
        });
    })
</script>

<div class="container-fluid top-panel">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            @Html.Partial("_StatusMessage", Model.StatusMessage)
            <form asp-action="" asp-controller="SystemAdmin" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
                <div class="panel-group">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h5>Create System User</h5>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div asp-validation-summary="All" class="text-danger col-sm-offset-4 col-sm-8"></div>
                            <div class="form-group-sm">
                                <label asp-for="Branch" class="control-label enquiry-text col-sm-4"></label>
                                <div class="col-sm-8">
                                    <select asp-for="Branch" asp-items="@{(SelectList)ViewData["Branches"]}" class="form-control" title="llsel">
                                        <option>--Select--</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group-sm">
                                <label asp-for="Staff" class="control-label enquiry-text col-sm-4"></label>
                                <div class="col-sm-8">
                                    <select asp-for="Staff" asp-items="@{(SelectList)ViewData["Customers"]}" class="form-control"></select>
                                </div>
                            </div>
                            <div class="form-group-sm">
                                <label asp-for="Username" class="control-label enquiry-text col-sm-4"></label>
                                <div class="col-sm-8">
                                    <input asp-for="Username" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group-sm">
                                <label asp-for="TransactionLimit" class="control-label enquiry-text col-sm-4"></label>
                                <div class="col-sm-8">
                                    <div class="input-group">
                                        <div class="input-group-addon"><i>NGN</i></div>
                                        <input asp-for="TransactionLimit" class="form-control" type="number" step="0.01" />
                                        <div class="input-group-addon"><i>0.00</i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group-sm">
                                <label asp-for="ApprovalLimit" class="control-label enquiry-text col-sm-4"></label>
                                <div class="col-sm-8">
                                    <div class="input-group">
                                        <div class="input-group-addon"><i>NGN</i></div>
                                        <input asp-for="ApprovalLimit" class="form-control" type="number" step="0.01" />
                                        <div class="input-group-addon"><i>0.00</i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group-sm">
                                <label asp-for="Role" class="control-label enquiry-text col-sm-4"></label>
                                <div class="col-sm-8">
                                    <select asp-for="Role" asp-items="@{(SelectList)ViewData["Roles"]}" class="form-control"></select>
                                </div>
                            </div>
                            <div class="form-group-sm">
                                <div class="col-sm-offset-4 col-sm-8">
                                    <div class="checkbox">
                                        <label asp-for="ActivateUser">
                                            <input asp-for="ActivateUser" />
                                            @Html.DisplayNameFor(m => m.ActivateUser)
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <a asp-action="SystemUsersListing" asp-controller="SystemAdmin"><b>View Users</b></a>
                            <button class="btn btn-primary btn-sm pull-right" type="submit" formaction="/SystemAdmin/SystemUsers">Add User</button>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h5>User Maintenance</h5>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="form-group-sm">
                                <label asp-for="MaintenanceType" class="control-label enquiry-text col-sm-4"></label>
                                <div class="col-sm-8">
                                    <select asp-for="MaintenanceType"  class="form-control">
                                        <option>CHANGE BRANCH</option>
                                        <option>CLEAR LOGIN</option>
                                        <option>DISABLE USER</option>
                                        <option>ENABLE USER</option>
                                        <option>EXTEND PASSWORD EXPIRY</option>
                                        <option>MAKE PASSWORD EXPIRE</option>
                                        <option>RESET PASSWORD</option>
                                        <option>UPDATE APPROVAL LIMIT</option>
                                        <option>UPDATE TRANSACTION LIMIT</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div id="LimitsModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">BankModel - Transaction/Approval Limit</h5>
                                    </div>
                                    <div class="modal-body">
                                        <div class="container-fluid">
                                            <div class="row">
                                                <label asp-for="LimitField" class="control-label enquiry-text col-sm-4"></label>
                                                <div class="col-sm-8">
                                                    <input asp-for="LimitField" class="form-control" type="number" step="0.001" required="required"/>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button name="btnLimitsClose" class="btn btn-primary btn-sm" data-dismiss="modal">Close</button>
                                        <button id="btnLimits" type="submit" class="btn btn-primary btn-sm" formaction="/SystemAdmin/SystemUserMaintenance">Maintain User</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="PasswordDaysModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">BankModel - Password Extension Days</h5>
                                    </div>
                                    <div class="modal-body">
                                        <div class="container-fluid">
                                            <div class="row">
                                                <label asp-for="PasswordDays" class="control-label enquiry-text col-sm-4"></label>
                                                <div class="col-sm-8">
                                                    <input asp-for="PasswordDays" class="form-control" type="number" step="1" required="required" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button name="btnPasswordDaysClose" class="btn btn-primary btn-sm" data-dismiss="modal">Close</button>
                                        <button id="btnPasswordDays" type="submit" class="btn btn-primary btn-sm" formaction="/SystemAdmin/SystemUserMaintenance">Maintain User</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="BranchModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">BankModel - Branch Network</h5>
                                    </div>
                                    <div class="modal-body">
                                        <div class="container-fluid">
                                            <div class="row">
                                                <label asp-for="Branch" class="control-label enquiry-text col-sm-4"></label>
                                                <div class="col-sm-8">
                                                    <select asp-for="Branch" asp-items="@{(SelectList)ViewData["Branches"]}" class="form-control" required="required">
                                                        <option>--Select--</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button name="btnBranchClose" class="btn btn-primary btn-sm" data-dismiss="modal">Close</button>
                                        <button id="btnBranch" type="submit" class="btn btn-primary btn-sm" formaction="/SystemAdmin/SystemUserMaintenance">Maintain User</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <button type="submit" class="btn btn-primary btn-sm pull-right" formaction="/SystemAdmin/SystemUserMaintenance">Maintain User</button>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>