BankModel.Web/Controllers/GeneralLedgerController.cs
using BankModel.Web.ViewModels;
using BankModel.Models;
using BankModel.Web.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;
using BankModel.Web.Services;

namespace BankModel.Web.Controllers
{
    public class GeneralLedgerController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IGeneralLedgerService _glService;
        private readonly IConfiguration _config;

        [TempData]
        public string StatusMessage { get; set; }
        private bool Result { get; set; }

        public GeneralLedgerController(
            UserManager<ApplicationUser> userManager,
            IGeneralLedgerService glService,
            IConfiguration config)
        {
            _userManager = userManager;
            _glService = glService;
            _config = config;
        }

        public GeneralLedgerController(IGeneralLedgerService glService)
        {
            _glService = new GeneralLedgerService(new ModelStateWrapper(this.ModelState));
        }



        //Chart of account details
        #region

        public JsonResult GetAccountSubHeads(string accountHead)
        {
            return Json(_glService.GetAccountSubHeads(accountHead));
        }

        [HttpGet]
        public async Task<IActionResult> ChartofAccountListing()
        {
            var user = await _userManager.GetUserAsync(User);
            return View(_glService.GetChartofAccountByUser(user.UserName));
        }

        [HttpGet]
        [Authorize(Policy = "ChartOfAccount")]
        public async Task<IActionResult> ChartofAccount()
        {
            var user = await _userManager.GetUserAsync(User);
            var branches = await _glService.GetBranchNamesByUser(user.UserName);
            ViewData["Branches"] = new SelectList(branches);
            ViewData["AccountHead"] = new SelectList(new[] { "ASSET", "LIABILITY", "INCOME", "EXPENSE" });
            var model = new ChartofAccountViewModel { StatusMessage = StatusMessage };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChartofAccount(ChartofAccountViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);
            if (!ModelState.IsValid)
            {
                var branches = await _glService.GetBranchNamesByUser(user.UserName);
                ViewData["Branches"] = new SelectList(branches);
                ViewData["AccountHead"] = new SelectList(new[] { "ASSET", "LIABILITY", "INCOME", "EXPENSE" });
                return View(model);
            }

            //If here, then its a new chart of account item
            model.ActionBy = user.UserName;
            Result = await _glService.CreateChartofAccountAsync(model);
            if (Result)
            {
                StatusMessage = _config.GetSection("Messages")["Success"];
                return RedirectToAction(nameof(ChartofAccount));
            }

            StatusMessage = "Error: Unable to create account sub head";
            return View(model);

        }

        [HttpGet]
        public async Task<IActionResult> UpdateChartofAccount(long id)
        {
            var user = await _userManager.GetUserAsync(User);
            var model = await _glService.GetChartofAccount(id);
            var branches = await _glService.GetBranchNamesByUser(user.UserName);
            ViewData["Branches"] = new SelectList(branches);
            ViewData["AccountHead"] = new SelectList(new[] { "ASSET", "LIABILITY", "INCOME", "EXPENSE" });
            return View(nameof(ChartofAccount), model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateChartofAccount(ChartofAccountViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);
            if (!ModelState.IsValid)
            {
                var branches = await _glService.GetBranchNamesByUser(user.UserName);
                ViewData["Branches"] = new SelectList(branches);
                ViewData["AccountHead"] = new SelectList(new[] { "ASSET", "LIABILITY", "INCOME", "EXPENSE" });
                return View(model);
            }

            //If here then its an update
            model.ActionBy = user.UserName;
            Result = await _glService.UpdateChartofAccountAsync(model);
            if (Result.Equals("Succeeded"))
            {
                StatusMessage = _config.GetSection("Messages")["Success"];
                return RedirectToAction(nameof(ChartofAccount));
            }

            StatusMessage = "Error: Unable to update chart of account";
            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = "ChartOfAccount")]
        public async Task<IActionResult> DropChartofAccount(int ID)
        {
            Result = await _glService.DropChartofAccountAsync(ID);
            if (Result.Equals("Succeeded"))
            {
                StatusMessage = _config.GetSection("Messages")["Success"];
                return RedirectToAction(nameof(ChartofAccountListing));
            }

            StatusMessage = "Error: Unable to delete branch";
            return RedirectToAction(nameof(ChartofAccountListing));
        }

        #endregion


    }
}

BankModel.Web/Views/GeneralLedger/ChartofAccount.cshtml
@model ChartofAccountViewModel
@using Microsoft.Extensions.Configuration
@inject IConfiguration config
@{
    ViewData["Title"] = config.GetSection("AppInfo")["Title"];
}

<script>
    $(document).ready(function () {
        $("#AccountHead").change(function () {
            if ($("#AccountHead").val() != "--Select--") {
                $.ajax
                    ({
                        url: "/GeneralLedger/GetAccountSubHeads",
                        type: "POST",
                        cache: false,
                        dataType: "JSON",
                        data: { accountHead: $("#AccountHead").val() },
                        success: function (item) {
                            $("#AccountSubHead").html("");
                            for (var i = 0; i < item.length; i++) {
                                $("#AccountSubHead").append("<option>" + item[i] + "</option>");
                            }
                        },
                        error: function (xhr, status) { alert(status); }
                    });
            };
        });
    })
</script>

<div class="container-fluid top-panel">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            @Html.Partial("_StatusMessage", Model.StatusMessage)
            <form asp-action="ChartofAccount" asp-controller="GeneralLedger" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h5>Create Chart of Account Items</h5>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div asp-validation-summary="All" class="text-danger col-sm-offset-4 col-sm-8"></div>
                        <div class="form-group-sm">
                            <label asp-for="Branch" class="control-label enquiry-text col-sm-4"></label>
                            <div class="col-sm-8">
                                <select asp-for="Branch" asp-items="@{(SelectList)ViewData["Branches"]}" class="form-control">
                                    <option>--Select--</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group-sm">
                            <label asp-for="AccountHead" class="control-label enquiry-text col-sm-4"></label>
                            <div class="col-sm-8">
                                <select asp-for="AccountHead" asp-items="@{(SelectList)ViewData["AccountHead"]}" class="form-control"></select>
                            </div>
                        </div>
                        <div class="form-group-sm">
                            <label asp-for="AccountSubHead" class="control-label enquiry-text col-sm-4"></label>
                            <div class="col-sm-8">
                                <select asp-for="AccountSubHead" asp-items="@{(SelectList)ViewData["AccountSubHead"]}" class="form-control"></select>
                            </div>
                        </div>
                        <div class="form-group-sm">
                            <label asp-for="AccountName" class="control-label enquiry-text col-sm-4"></label>
                            <div class="col-sm-8">
                                <input asp-for="AccountName" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group-sm"><input asp-for="ID" class="hidden" /></div>
                    </div>
                    <div class="panel-footer">
                        <a asp-action="ChartofAccountListing" asp-controller="GeneralLedger">Chart of Account Listing</a>
                        <button class="btn btn-primary btn-sm pull-right" type="submit">Add Chart Item</button>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

BankModel.Web/Views/GeneralLedger/ChartofAccountListing.cshtml
@model IEnumerable<BranchChartofAccountViewModel>
@using BankModel.Web.Interfaces
@inject IGeneralLedgerService GLService
@{
    ViewData["Title"] = "Setup";
}

<div class="container-fluid top-panel">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <h5>Branch Chart of Account Listing</h5>
                    </div>
                </div>
                <div class="panel-body">
                    <table data-toggle="table" data-class="table table-condensed" 
                           data-striped="true" data-pagination="true" data-search="true" data-show-header="true"
                           data-show-column="true" data-show-refresh="true" data-show-toggle="true"
                           data-show-pagination-switch="true" data-id-field="Id">
                        <thead>
                            <tr>
                                <th data-field="Id" class="hidden">ID</th>
                                <th data-field="AccountCode">Account Number</th>
                                <th data-field="AccountName">Account Name</th>
                                <th data-field="AccountHead">Account Head</th>
                                <th data-field="AccountSubHead">Account SubHead</th>
                                <th data-field="action"><i class="fa fa-cog"></i></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class="hidden">@item.ID</td>
                                    <td>@item.AccountNo</td>
                                    <td>@item.AccountName</td>
                                    <td>@item.AccountHead</td>
                                    <td>@item.AccountSubHead</td>
                                    <td>
                                        @if (item.Status == "ACTIVE")
                                        {
                                            var accountInUse = await GLService.IsChartofAccountInUse(item.ID);
                                            @if (!accountInUse)
                                            {
                                                <a asp-action="UpdateChartofAccount" asp-controller="GeneralLedger" asp-route-id="@item.ID" class="btn btn-info btn-sm"><i class="fa fa-pencil"> Update</i></a>
                                            }
                                        }
                                        @if(item.Status == "PENDING")
                                        {
                                            <a asp-action="UpdateChartofAccount" asp-controller="GeneralLedger" asp-route-id="@item.ID" class="btn btn-info btn-sm"><i class="fa fa-pencil"> Update</i></a>
                                            <a asp-action="DropChartofAccount" asp-controller="GeneralLedger" asp-route-id="@item.ID" class="btn btn-danger btn-sm"><i class="fa fa-trash"> Drop</i></a>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                    <a asp-action="ChartofAccount" asp-controller="GeneralLedger" class="btn btn-primary btn-sm pull-right">Back</a>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>